// ============================================================================
// TollGate — AI Engine Client
//
// Calls the Python FastAPI + LangGraph AI engine. No mocks — AI_ENGINE_URL
// must be set in .env (e.g. http://localhost:8000).
// ============================================================================

import type { TestResult } from "./types";

// ── Types ───────────────────────────────────────────────────────────────────

export interface FailureAnalysis {
  rca_report: string;
  proposed_fix: string;
  confidence: number;
}

export interface HealerResult {
  session_id: string;
  decision: string;
  rca_type: string | null;
  rca_report: string | null;
  proposed_fix: string | null;
  proposed_patch: string | null;
  confidence_score: number | null;
  fix_branch: string | null;
  target_files: string[] | null;
  dispatch_action: string | null;
  dispatch_result_type: string | null;
  dispatch_result_url: string | null;
  dispatch_result_number: number | null;
}

export interface FileEdit {
  file: string;
  search: string;
  replace: string;
}

export interface HealerOnlyResult {
  session_id: string;
  decision: string;
  rca_type: string | null;
  rca_report: string | null;
  proposed_fix: string | null;
  proposed_patch: string | null;
  file_edits: FileEdit[] | null;
  confidence_score: number | null;
  fix_branch: string | null;
  target_files: string[] | null;
  rag_healer_matches: number;
  rag_healer_insights: string;
}

// ── AI Engine Client ────────────────────────────────────────────────────────

export class AIEngineClient {
  private baseUrl: string | null;

  constructor() {
    this.baseUrl = process.env.AI_ENGINE_URL || null;
  }

  get isConnected(): boolean {
    return this.baseUrl !== null;
  }

  // ── Test Plan Generation (Architect Agent) ────────────────────────────────

  async generateTestPlan(
    codeContext: string,
    changedFiles: string[],
    targetUrl: string,
    gitDiff?: string
  ): Promise<{
    test_plan: string;
    rag_architect_matches: number;
    rag_architect_insights: string;
  }> {
    if (!this.baseUrl) {
      throw new Error(
        "AI_ENGINE_URL is required. No mocks — set AI_ENGINE_URL in .env to the AI engine service URL."
      );
    }
    const response = await this.callRemote<{
      test_plan: string;
      provider: string;
      rag_architect_matches: number;
      rag_architect_insights: string;
    }>("/generate-test-plan", {
      code_context: codeContext,
      changed_files: changedFiles,
      target_url: targetUrl,
      git_diff: gitDiff ?? "",
    }, 90_000);
    console.log(`[AI Engine] Test plan generated by: ${response.provider}`);
    return {
      test_plan: response.test_plan,
      rag_architect_matches: response.rag_architect_matches ?? 0,
      rag_architect_insights: response.rag_architect_insights ?? "",
    };
  }

  // ── Failure Analysis (Healer Agent) ───────────────────────────────────────

  async analyzeFailure(
    testResults: TestResult[],
    codeContext: string,
    diff: string
  ): Promise<FailureAnalysis> {
    if (!this.baseUrl) {
      throw new Error(
        "AI_ENGINE_URL is required. No mocks — set AI_ENGINE_URL in .env."
      );
    }
    return this.callRemote("/analyze-failure", {
      test_results: testResults,
      code_context: codeContext,
      diff,
    });
  }

  // ── Full Healer + Courier pipeline (Healer Agent via LangGraph) ────────────

  /**
   * Runs the full LangGraph pipeline on the AI engine with pre-supplied
   * test_results so it skips re-running tests and goes straight to:
   *   decision → Healer (RCA + fix) → courier_decision → courier_execute
   */
  async runHealer(opts: {
    repoUrl: string;
    changedFiles: string[];
    targetUrl: string;
    sessionId: string;
    testResults: TestResult[];
    gitDiff?: string;
    branch?: string;
  }): Promise<HealerResult> {
    if (!this.baseUrl) {
      throw new Error(
        "AI_ENGINE_URL is required. No mocks — set AI_ENGINE_URL in .env."
      );
    }

    return this.callRemote<HealerResult>("/run-pipeline", {
      repo_url: opts.repoUrl,
      changed_files: opts.changedFiles,
      target_url: opts.targetUrl,
      session_id: opts.sessionId,
      test_results: opts.testResults,
      git_diff: opts.gitDiff ?? "",
      branch: opts.branch ?? "main",
    }, 120_000);
  }

  // ── Healer Only (RCA + patch, no courier) ────────────────────────────────

  /**
   * Runs only the Healer agent (decision → healer → END) without courier.
   * Returns the RCA analysis and proposed patch so the orchestrator can
   * bundle code fixes into a unified PR alongside test scripts.
   */
  async runHealerOnly(opts: {
    repoUrl: string;
    changedFiles: string[];
    targetUrl: string;
    sessionId: string;
    testResults: TestResult[];
    gitDiff?: string;
    branch?: string;
    /** Verbatim PR-head file text from GitHub — enables exact search/replace application. */
    prHeadFileContents?: Array<{ path: string; content: string }>;
  }): Promise<HealerOnlyResult> {
    if (!this.baseUrl) {
      throw new Error(
        "AI_ENGINE_URL is required. No mocks — set AI_ENGINE_URL in .env."
      );
    }

    return this.callRemote<HealerOnlyResult>("/run-healer", {
      repo_url: opts.repoUrl,
      changed_files: opts.changedFiles,
      target_url: opts.targetUrl,
      session_id: opts.sessionId,
      test_results: opts.testResults,
      git_diff: opts.gitDiff ?? "",
      branch: opts.branch ?? "main",
      pr_head_file_contents: opts.prHeadFileContents ?? [],
    }, 120_000);
  }

  // ── Store fix + test plan in RAG vector DB ────────────────────────────────

  async storeFixInRAG(data: {
    repoUrl: string;
    sessionId: string;
    rcaType?: string;
    rcaReport?: string;
    proposedFix?: string;
    proposedPatch?: string;
    fileEdits?: FileEdit[];
    targetFiles?: string[];
    fixBranch?: string;
    confidenceScore?: number;
    changedFiles?: string[];
    gitDiff?: string;
    testPlan?: string;
    totalTests?: number;
    passedTests?: number;
    failedTestsCount?: number;
    failedTests?: { name: string; error: string }[];
    prUrl?: string;
    prNumber?: number;
  }): Promise<{ fix_stored: boolean; plan_stored: boolean }> {
    if (!this.baseUrl) {
      console.warn("[AI Engine] storeFixInRAG: AI_ENGINE_URL not set, skipping.");
      return { fix_stored: false, plan_stored: false };
    }

    try {
      return await this.callRemote<{ fix_stored: boolean; plan_stored: boolean }>("/store-fix", {
        repo_url: data.repoUrl,
        session_id: data.sessionId,
        rca_type: data.rcaType ?? "",
        rca_report: data.rcaReport ?? "",
        proposed_fix: data.proposedFix ?? "",
        proposed_patch: data.proposedPatch ?? "",
        file_edits: (data.fileEdits ?? []).map(e => ({
          file_path: e.file,
          search: e.search,
          replace: e.replace,
        })),
        target_files: data.targetFiles ?? [],
        fix_branch: data.fixBranch ?? "",
        confidence_score: data.confidenceScore ?? 0,
        changed_files: data.changedFiles ?? [],
        git_diff: data.gitDiff ?? "",
        test_plan: data.testPlan ?? "",
        total_tests: data.totalTests ?? 0,
        passed_tests: data.passedTests ?? 0,
        failed_tests_count: data.failedTestsCount ?? 0,
        failed_tests: data.failedTests ?? [],
        pr_url: data.prUrl ?? "",
        pr_number: data.prNumber,
      }, 120_000);
    } catch (err) {
      console.error("[AI Engine] storeFixInRAG failed:", err);
      return { fix_stored: false, plan_stored: false };
    }
  }

  // ── Remote call to AI Engine ─────────────────────────────────────────────

  private async callRemote<T>(endpoint: string, body: unknown, timeoutMs = 60_000): Promise<T> {
    const url = `${this.baseUrl}${endpoint}`;
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(timeoutMs),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`AI Engine error (${res.status}): ${text}`);
    }

    return res.json() as Promise<T>;
  }

}

// ── Singleton ───────────────────────────────────────────────────────────────

export const aiEngine = new AIEngineClient();
