// ============================================================================
// TollGate — Test Writer
//
// Converts AI-generated test plans + execution results into real Playwright
// test files (.spec.ts) that developers can review, run, and maintain.
// Also generates a rich PR body with results, snapshots, and pipeline steps.
// ============================================================================

import type { TestResult, TestRunOutput } from "./types";
import type { HealerOnlyResult } from "./ai-engine-client";

// ── Types ───────────────────────────────────────────────────────────────────

export interface GeneratedTestFile {
  /** File path relative to repo root (e.g. tests/e2e/landing-page.spec.ts) */
  path: string;
  /** Full file content */
  content: string;
}

interface TestSuite {
  name: string;
  steps: string[];
}

// ── Test Code Generator ─────────────────────────────────────────────────────

/**
 * Parse the markdown test plan into individual test suites.
 */
function parseTestSuites(testPlan: string): TestSuite[] {
  const suites: TestSuite[] = [];
  let currentSuite: TestSuite | null = null;

  for (const line of testPlan.split("\n")) {
    const trimmed = line.trim();

    // Match suite headers: "## Test Suite 1: Landing Page" or "## 1. Landing Page"
    const suiteMatch = trimmed.match(/^##\s+(?:Test Suite \d+:\s*)?(?:\d+\.\s*)?(.+)/i);
    if (suiteMatch && !trimmed.startsWith("###")) {
      if (currentSuite) suites.push(currentSuite);
      currentSuite = { name: suiteMatch[1].trim(), steps: [] };
      continue;
    }

    // Match numbered steps
    const stepMatch = trimmed.match(/^(?:\d+\.\s+|-\s+)(.+)$/);
    if (stepMatch && currentSuite) {
      currentSuite.steps.push(stepMatch[1]);
    }
  }

  if (currentSuite) suites.push(currentSuite);
  return suites;
}

/**
 * Convert a suite name to a valid filename slug.
 */
function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 50);
}

/**
 * Convert a test step description into Playwright test code.
 * @param targetUrl - base URL used to resolve relative navigation targets
 */
function stepToCode(step: string, indent: string, targetUrl: string): string {
  const lower = step.toLowerCase();

  // Navigate
  const navMatch = step.match(/navigate\s+to\s+(\S+)/i);
  if (navMatch) {
    const target = navMatch[1];
    const isAbsolute = /^https?:\/\//i.test(target);
    const resolved = isAbsolute
      ? target
      : `${targetUrl.replace(/\/$/, "")}/${target.replace(/^\//, "")}`;
    return `${indent}await page.goto('${resolved}');`;
  }

  // Snapshot
  if (lower.includes("snapshot") || lower.includes("capture")) {
    return `${indent}await expect(page).toHaveScreenshot();`;
  }

  // Assert contains
  const assertMatch = step.match(/assert\s+(?:the\s+)?(?:page\s+)?contains?\s+["']?(.+?)["']?$/i);
  if (assertMatch) {
    const text = assertMatch[1].replace(/'/g, "\\'");
    return `${indent}await expect(page.getByText('${text}')).toBeVisible();`;
  }

  // Click
  const clickMatch = step.match(/click\s+(?:the\s+|on\s+)?["'](.+?)["']\s*(?:button|link|element)?/i);
  if (clickMatch) {
    return `${indent}await page.getByRole('button', { name: '${clickMatch[1]}' }).or(page.getByRole('link', { name: '${clickMatch[1]}' })).click();`;
  }
  if (lower.includes("click")) {
    const generic = step.replace(/^click\s+(?:the\s+|on\s+)?/i, "").replace(/\s*(?:button|link|element)\s*$/i, "");
    return `${indent}await page.getByText('${generic.replace(/'/g, "\\'")}').click();`;
  }

  // Type
  const typeMatch = step.match(/type\s+["'](.+?)["']\s+(?:into|in)\s+(?:the\s+)?(.+)/i);
  if (typeMatch) {
    const value = typeMatch[1].replace(/'/g, "\\'");
    const field = typeMatch[2].replace(/\s*field\s*$/i, "").trim();
    return `${indent}await page.getByLabel('${field}').or(page.getByPlaceholder('${field}')).fill('${value}');`;
  }

  // Wait
  const waitMatch = step.match(/wait\s+(?:for\s+)?(\d+)\s*(?:seconds?|ms)?/i);
  if (waitMatch) {
    let ms = parseInt(waitMatch[1], 10);
    if (lower.includes("second")) ms *= 1000;
    return `${indent}await page.waitForTimeout(${ms});`;
  }

  // Hover
  const hoverMatch = step.match(/hover\s+(?:over\s+)?(?:the\s+)?["']?(.+?)["']?$/i);
  if (hoverMatch) {
    return `${indent}await page.getByText('${hoverMatch[1].replace(/'/g, "\\'")}').hover();`;
  }

  // Fallback: comment
  return `${indent}// TODO: ${step}`;
}

/**
 * Generate a complete Playwright test file for a test suite.
 */
function generateSpecFile(suite: TestSuite, targetUrl: string): string {
  const lines: string[] = [];
  const indent = "  ";

  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`// Auto-generated by TollGate Pipeline`);
  lines.push(`// ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`test.describe('${suite.name.replace(/'/g, "\\'")}', () => {`);
  lines.push(`${indent}test('should pass all checks', async ({ page }) => {`);
  lines.push(`${indent}${indent}await page.goto('${targetUrl}');`);
  lines.push(``);

  for (const step of suite.steps) {
    lines.push(`${indent}${indent}// ${step}`);
    lines.push(stepToCode(step, `${indent}${indent}`, targetUrl));
    lines.push(``);
  }

  lines.push(`${indent}});`);
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate Playwright test files from a test plan.
 */
export function generateTestFiles(
  testPlan: string,
  targetUrl: string
): GeneratedTestFile[] {
  const suites = parseTestSuites(testPlan);
  const files: GeneratedTestFile[] = [];

  for (const suite of suites) {
    if (suite.steps.length === 0) continue;
    const slug = toSlug(suite.name);
    files.push({
      path: `tests/e2e/${slug}.spec.ts`,
      content: generateSpecFile(suite, targetUrl),
    });
  }

  // Also write the raw test plan as markdown for reference
  files.push({
    path: `tests/e2e/TEST_PLAN.md`,
    content: `# TollGate — Auto-Generated Test Plan\n\n> Generated on ${new Date().toISOString()}\n\n${testPlan}\n`,
  });

  return files;
}

/**
 * Build a rich PR body with:
 * - Pipeline steps summary
 * - Test results table
 * - Accessibility snapshots from failures
 * - Generated test file listing
 */
export interface PRBodyOptions {
  /** Original PR number this fix is for */
  originalPrNumber?: number;
  /** Original PR title */
  originalPrTitle?: string;
  /** Branch this fix was forked from (original PR's head) */
  sourceBranch?: string;
  /** Branch this PR targets (original PR's base, e.g. main) */
  targetBranch?: string;
  /** Files changed in the original PR (from diff) */
  originalChangedFiles?: string[];
  /** Issue number created by the Courier for this failure (links PR to issue) */
  issueNumber?: number;
}

export function buildPRBody(
  sessionId: string,
  testPlan: string,
  results: TestRunOutput,
  files: GeneratedTestFile[],
  codeContextLength: number,
  healerResult?: HealerOnlyResult | null,
  prOptions?: PRBodyOptions,
  postFixResults?: TestRunOutput | null
): string {
  const lines: string[] = [];
  const hasHealerFix = ((healerResult?.file_edits?.length ?? 0) > 0 || healerResult?.proposed_patch?.trim()) && (healerResult?.confidence_score ?? 0) > 0.5;
  const fixedFiles = healerResult?.file_edits?.map(e => e.file) ?? [];

  // Header
  if (hasHealerFix) {
    lines.push(`## 🛡️ TollGate — Auto-Fix + E2E Tests`);
  } else {
    lines.push(`## 🛡️ TollGate — Auto-Generated Tests`);
  }
  lines.push(``);
  lines.push(`**Session**: \`${sessionId}\``);
  lines.push(`**Generated**: ${new Date().toISOString()}`);
  if (prOptions?.originalPrNumber) {
    lines.push(`**Testing PR**: #${prOptions.originalPrNumber}${prOptions.originalPrTitle ? ` — ${prOptions.originalPrTitle}` : ""}`);
  }
  if (prOptions?.issueNumber) {
    lines.push(`**Fixes**: #${prOptions.issueNumber}`);
    lines.push(``);
    lines.push(`Closes #${prOptions.issueNumber}`);
  }
  lines.push(``);

  // What's in this PR — distinguishes original files from TollGate additions
  if (prOptions?.originalPrNumber) {
    lines.push(`### 📦 What's In This PR`);
    lines.push(``);
    lines.push(`This PR was branched from \`${prOptions.sourceBranch ?? "unknown"}\` (PR #${prOptions.originalPrNumber}) and targets \`${prOptions.targetBranch ?? "main"}\`.`);
    lines.push(`It contains **all original PR files** plus TollGate additions:`);
    lines.push(``);
    lines.push(`| Category | Files | Description |`);
    lines.push(`|----------|-------|-------------|`);
    if (prOptions.originalChangedFiles?.length) {
      lines.push(`| Original PR | ${prOptions.originalChangedFiles.length} files | From PR #${prOptions.originalPrNumber} (unchanged) |`);
    }
    if (fixedFiles.length > 0) {
      lines.push(`| Healer Fixes | ${fixedFiles.length} files | Code changes to resolve test failures |`);
    }
    lines.push(`| Test Files | ${files.length} files | Auto-generated E2E tests |`);
    lines.push(``);

    if (fixedFiles.length > 0) {
      lines.push(`> **Only ${fixedFiles.length + files.length} file(s) were added/modified by TollGate.** All other files are carried over from the original PR.`);
      lines.push(``);
    }
  }

  // Healer RCA + Fixes (the core section)
  if (healerResult && results.failed > 0) {
    lines.push(`### 🩺 Root Cause Analysis`);
    lines.push(``);
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| RCA Type | \`${healerResult.rca_type ?? "unknown"}\` |`);
    lines.push(`| Confidence | ${((healerResult.confidence_score ?? 0) * 100).toFixed(0)}% |`);
    if (healerResult.target_files?.length) {
      lines.push(`| Target Files | ${healerResult.target_files.map(f => `\`${f}\``).join(", ")} |`);
    }
    lines.push(``);

    if (healerResult.rca_report) {
      lines.push(`**Analysis**: ${healerResult.rca_report}`);
      lines.push(``);
    }

    if (healerResult.proposed_fix) {
      lines.push(`**Proposed Fix**: ${healerResult.proposed_fix}`);
      lines.push(``);
    }

    // Fixes applied — show clearly what changed
    if (hasHealerFix && healerResult.file_edits?.length) {
      lines.push(`### 🔧 Code Fixes Applied`);
      lines.push(``);
      lines.push(`The Healer agent modified **${healerResult.file_edits.length} file(s)** to resolve failing tests:`);
      lines.push(``);

      for (const edit of healerResult.file_edits) {
        lines.push(`#### \`${edit.file}\``);
        lines.push("```diff");
        for (const searchLine of edit.search.split("\n")) {
          lines.push(`- ${searchLine}`);
        }
        for (const replaceLine of edit.replace.split("\n")) {
          lines.push(`+ ${replaceLine}`);
        }
        lines.push("```");
        lines.push(``);
      }
    } else if (hasHealerFix && healerResult?.proposed_patch) {
      lines.push(`### 🔧 Code Fixes Applied`);
      lines.push(``);
      lines.push("```diff");
      lines.push(healerResult.proposed_patch);
      lines.push("```");
      lines.push(``);
    }
  }

  // ── Post-fix verification results (if available) ──
  if (postFixResults && hasHealerFix) {
    const postPassRate = postFixResults.total > 0 ? ((postFixResults.passed / postFixResults.total) * 100).toFixed(0) : "0";
    lines.push(`### ✅ Test Results (after fix)`);
    lines.push(``);
    lines.push(`Tests were re-run after applying the Healer's code fixes:`);
    lines.push(``);
    lines.push(`| Metric | Before Fix | After Fix |`);
    lines.push(`|--------|-----------|-----------|`);
    lines.push(`| ✅ Passed | ${results.passed}/${results.total} | **${postFixResults.passed}/${postFixResults.total}** |`);
    lines.push(`| ❌ Failed | ${results.failed} | **${postFixResults.failed}** |`);
    lines.push(`| Pass Rate | ${((results.passed / Math.max(results.total, 1)) * 100).toFixed(0)}% | **${postPassRate}%** |`);
    lines.push(`| Duration | ${results.duration_ms}ms | ${postFixResults.duration_ms}ms |`);
    lines.push(``);

    if (postFixResults.failed === 0) {
      lines.push(`> 🎉 **All tests pass after the fix!** This PR is ready for review.`);
    } else {
      lines.push(`> ⚠️ **${postFixResults.failed} test(s) still failing** after the fix. Manual review recommended.`);
    }
    lines.push(``);

    // Post-fix step-by-step
    lines.push(`| # | Test Step | Before | After |`);
    lines.push(`|---|-----------|--------|-------|`);
    for (let i = 0; i < postFixResults.results.length; i++) {
      const post = postFixResults.results[i];
      const pre = results.results[i];
      const preIcon = pre?.status === "passed" ? "✅" : pre?.status === "failed" ? "❌" : "⏭️";
      const postIcon = post.status === "passed" ? "✅" : post.status === "failed" ? "❌" : "⏭️";
      const name = post.name.replace(/^Step \d+: /, "");
      const changed = pre?.status !== post.status ? " 🔄" : "";
      lines.push(`| ${i + 1} | ${name} | ${preIcon} | ${postIcon}${changed} |`);
    }
    lines.push(``);

  } else {
    // No post-fix results — show standard results
    const passRate = results.total > 0 ? ((results.passed / results.total) * 100).toFixed(0) : "0";

    if (hasHealerFix && results.failed > 0) {
      lines.push(`### 📊 Test Results (before fix)`);
      lines.push(``);
      lines.push(`> These results are from the initial test run against the **buggy code**.`);
      lines.push(`> The Healer's code fixes above target these failures.`);
      lines.push(``);
    } else {
      lines.push(`### 📊 Test Results`);
      lines.push(``);
    }

    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Tests | ${results.total} |`);
    lines.push(`| ✅ Passed | ${results.passed} |`);
    lines.push(`| ❌ Failed | ${results.failed} |`);
    lines.push(`| Pass Rate | ${passRate}% |`);
    lines.push(`| Duration | ${results.duration_ms}ms |`);
    lines.push(``);

    // Step-by-step results
    lines.push(`### 📋 Step-by-Step Results`);
    lines.push(``);
    lines.push(`| # | Test Step | Status | Duration |`);
    lines.push(`|---|-----------|--------|----------|`);
    for (let i = 0; i < results.results.length; i++) {
      const r = results.results[i];
      const icon = r.status === "passed" ? "✅" : r.status === "failed" ? "❌" : "⏭️";
      const name = r.name.replace(/^Step \d+: /, "");
      lines.push(`| ${i + 1} | ${name} | ${icon} ${r.status} | ${r.duration_ms}ms |`);
    }
    lines.push(``);
  }

  // Failed test details with errors (from pre-fix or only run)
  const sourceResults = postFixResults ?? results;
  const failures = sourceResults.results.filter((r) => r.status === "failed");
  if (failures.length > 0) {
    lines.push(`### 🔍 Failure Details`);
    lines.push(``);
    for (const f of failures) {
      lines.push(`<details>`);
      lines.push(`<summary>❌ ${f.name}</summary>`);
      lines.push(``);
      if (f.error) {
        lines.push(`**Error**: \`${f.error}\``);
        lines.push(``);
      }
      if (f.accessibility_snapshot) {
        lines.push(`**Page Snapshot** (accessibility tree at time of failure):`);
        lines.push(``);
        const snap = f.accessibility_snapshot.length > 2000
          ? f.accessibility_snapshot.substring(0, 2000) + "\n... (truncated)"
          : f.accessibility_snapshot;
        lines.push("```yaml");
        lines.push(snap);
        lines.push("```");
      }
      lines.push(`</details>`);
      lines.push(``);
    }
  }

  // Pipeline steps
  lines.push(`### 🔄 Pipeline Steps`);
  lines.push(``);
  lines.push(`| Step | Description | Status |`);
  lines.push(`|------|-------------|--------|`);
  lines.push(`| 1 | GitHub MCP — Read repository code (${codeContextLength} chars) | ✅ |`);
  lines.push(`| 2 | AI Engine — Generate test plan (${testPlan.split("\n").length} lines) | ✅ |`);
  lines.push(`| 3 | Playwright MCP — Execute tests in headless browser | ✅ |`);
  lines.push(`| 4 | Healer — Root cause analysis${hasHealerFix ? " + code fix" : ""} | ${healerResult ? "✅" : "⏭️"} |`);
  lines.push(`| 5 | Test Writer — Generate Playwright spec files | ✅ |`);
  lines.push(`| 6 | Courier — Push ${hasHealerFix ? "fixes + tests" : "tests"} & open this PR | ✅ |`);
  if (postFixResults && hasHealerFix) {
    lines.push(`| 7 | Verification — Re-run tests after fix | ${postFixResults.failed === 0 ? "✅" : "⚠️"} |`);
  }
  lines.push(``);

  // Generated files listing
  lines.push(`### 📁 Generated Test Files`);
  lines.push(``);
  for (const f of files) {
    lines.push(`- \`${f.path}\``);
  }
  lines.push(``);

  // Test plan (collapsed)
  lines.push(`<details>`);
  lines.push(`<summary>📝 AI-Generated Test Plan</summary>`);
  lines.push(``);
  lines.push(testPlan);
  lines.push(``);
  lines.push(`</details>`);
  lines.push(``);

  // Footer
  lines.push(`---`);
  if (hasHealerFix) {
    lines.push(`*This PR was created automatically by the TollGate pipeline. Code fixes were generated by the Healer agent. Tests were generated by the Architect agent and executed via Playwright MCP.*`);
  } else {
    lines.push(`*This PR was created automatically by the TollGate pipeline. Tests were generated by the AI Architect agent and executed via Playwright MCP.*`);
  }

  return lines.join("\n");
}
